export const SET_LOGINED = 'SET_LOGINED'

export const REMOVE_LOGINED = 'REMOVE_LOGINED'

export const SET_USER = 'SET_USER'

export const SET_USER_AUTHS = 'SET_USER_AUTHS'

export const SET_STOP_TIME = 'SET_STOP_TIME'

export const SET_SIDEBAR_LIST = 'SET_SIDEBAR_LIST'

export const SET_DEFAULT_ACTIVE_TAB = 'SET_DEFAULT_ACTIVE_TAB'
